
import dal.QuestionDAO;
import java.awt.Button;
import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import model.Question;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author thuy
 */
public class MainScreen extends javax.swing.JFrame implements ActionListener, Runnable {

    /**
     * Creates new form MainScreen
     */
    int time = 10;
    boolean done = false;
    boolean enable = true;

    private void displayTime() {
        int hh = time / 3600;
        int mm = time / 3600 % 60;
        int ss = time % 60;
        lblTimeLeft.setText("Time Left: " + hh + ":" + mm + ":" + ss);
    }

    @Override
    public void run() {
        while (time > 0 && !done) {
            displayTime();
            time--;
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        displayTime();
        ResultDialog result = new ResultDialog(this, true);
        result.setVisible(true);
        if (!enable) {
            System.exit(0);
        }
    }

    ArrayList<Question> questionList;
    HashMap<Question, QuestionComponent> questionComponent = new HashMap<>();
    HashMap<JButton, Question> questionBtn = new HashMap<>();

    public MainScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Tsunami-Ques");

        panelQuestionComponents.setLayout(new CardLayout());
        panelQuestionButtons.setLayout(new FlowLayout());
        QuestionDAO db = new QuestionDAO();
        questionList = db.getQuestionList();
        for (int i = 0; i < questionList.size(); ++i) {
            QuestionComponent qc = new QuestionComponent(questionList.get(i));
            questionComponent.put(questionList.get(i), qc);
            panelQuestionComponents.add(questionList.get(i).getId() + "", qc);

            JButton btnQues = new JButton("" + (i + 1));
            panelQuestionButtons.add(btnQues);
            questionBtn.put(btnQues, questionList.get(i));
            btnQues.addActionListener(this);
        }
        this.displayQuestion(questionList.get(0));

        Thread t = new Thread(this);
        t.start();
    }

    public void displayQuestion(Question q) {
        CardLayout layout = (CardLayout) panelQuestionComponents.getLayout();
        layout.show(panelQuestionComponents, q.getId() + ""); //(panel that contain layout, name of layout)
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton btn = (JButton) e.getSource();
        this.displayQuestion(questionBtn.get(btn));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelQuestionComponents = new javax.swing.JPanel();
        panelQuestionButtons = new javax.swing.JPanel();
        lblTimeLeft = new javax.swing.JLabel();
        btnFinish = new javax.swing.JButton();
        cbxConfirmDone = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        panelQuestionComponents.setBackground(new java.awt.Color(255, 204, 204));
        panelQuestionComponents.setPreferredSize(new java.awt.Dimension(800, 487));

        javax.swing.GroupLayout panelQuestionComponentsLayout = new javax.swing.GroupLayout(panelQuestionComponents);
        panelQuestionComponents.setLayout(panelQuestionComponentsLayout);
        panelQuestionComponentsLayout.setHorizontalGroup(
            panelQuestionComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelQuestionComponentsLayout.setVerticalGroup(
            panelQuestionComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        panelQuestionButtons.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout panelQuestionButtonsLayout = new javax.swing.GroupLayout(panelQuestionButtons);
        panelQuestionButtons.setLayout(panelQuestionButtonsLayout);
        panelQuestionButtonsLayout.setHorizontalGroup(
            panelQuestionButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelQuestionButtonsLayout.setVerticalGroup(
            panelQuestionButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        lblTimeLeft.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTimeLeft.setText("jLabel1");

        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        cbxConfirmDone.setText("I'm done");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelQuestionComponents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelQuestionButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTimeLeft)
                                .addGap(73, 73, 73))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 596, Short.MAX_VALUE)
                        .addComponent(cbxConfirmDone)
                        .addGap(48, 48, 48)
                        .addComponent(btnFinish)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTimeLeft)
                .addGap(18, 18, 18)
                .addComponent(panelQuestionComponents, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelQuestionButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinish)
                    .addComponent(cbxConfirmDone))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        if (cbxConfirmDone.isSelected()) {
            done = true;
        }
    }//GEN-LAST:event_btnFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JCheckBox cbxConfirmDone;
    private javax.swing.JLabel lblTimeLeft;
    private javax.swing.JPanel panelQuestionButtons;
    private javax.swing.JPanel panelQuestionComponents;
    // End of variables declaration//GEN-END:variables

}
