
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import model.Answer;
import model.Question;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author thuy
 */
public class QuestionComponent extends javax.swing.JPanel {

    /**
     * Creates new form QuestionComponent
     */
    Question q;
    ArrayList<Component> answerComponents = new ArrayList();

    public QuestionComponent(Question q) {
        initComponents();
        this.q = q;
        txtQuestionContent.setText(q.getContent());
        ButtonGroup groupRadAnswer = new ButtonGroup();
        
        for (int i = 0; i < q.getAnswerList().size(); i++) {
            Answer a = q.getAnswerList().get(i);
            
            if (q.isMultiChoice()) {
                JCheckBox cbxAnswer = new JCheckBox(a.getContent());
                answerComponents.add(cbxAnswer);
                panelAnswer.add(cbxAnswer);
            } else {
                JRadioButton radAnswer = new JRadioButton(a.getContent());
                answerComponents.add(radAnswer);
                panelAnswer.add(radAnswer);
                groupRadAnswer.add(radAnswer);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQuestionContent = new javax.swing.JTextField();
        panelAnswer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(800, 487));

        txtQuestionContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuestionContentActionPerformed(evt);
            }
        });

        panelAnswer.setBackground(new java.awt.Color(204, 204, 255));
        panelAnswer.setLayout(new javax.swing.BoxLayout(panelAnswer, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuestionContent, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addComponent(panelAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtQuestionContent, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuestionContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuestionContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuestionContentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelAnswer;
    private javax.swing.JTextField txtQuestionContent;
    // End of variables declaration//GEN-END:variables
}
